# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento (RG/BI)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Foto')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('matricula', models.CharField(help_text='Gerada automaticamente', max_length=20, unique=True, verbose_name='Matrícula')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'Suspenso'), ('TRANCADO', 'Trancado'), ('FORMADO', 'Formado'), ('TRANSFERIDO', 'Transferido'), ('DESISTENTE', 'Desistente')], default='ATIVO', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Encarregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, unique=True, verbose_name='Telemóvel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('grau_parentesco', models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Avô', 'Avô'), ('Avó', 'Avó'), ('Outro', 'Outro')], max_length=20, verbose_name='Grau de Parentesco')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Encarregado',
                'verbose_name_plural': 'Encarregados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Crédito')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_corrente', to='secretaria.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Conta Corrente',
                'verbose_name_plural': 'Contas Correntes',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='secretaria.encarregado', verbose_name='Encarregado'),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da Fatura')),
                ('tipo', models.CharField(choices=[('MENSALIDADE', 'Mensalidade'), ('MATRICULA', 'Matrícula'), ('MATERIAL', 'Material Didático'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Tipo')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Original')),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Atual')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('VENCIDO', 'VENCIDO'), ('PAGO', 'PAGO')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='secretaria.aluno', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='PreMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso')),
            ],
            options={
                'verbose_name': 'Pré‑Matrícula',
                'verbose_name_plural': 'Pré‑Matrículas',
                'ordering': ['-data_solic'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=20, unique=True, verbose_name='Número do Recibo')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERÊNCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], max_length=15, verbose_name='Forma de Pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='secretaria.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='FaturaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.fatura')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.servico')),
            ],
            options={
                'unique_together': {('fatura', 'servico')},
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='itens',
            field=models.ManyToManyField(through='secretaria.FaturaServico', to='secretaria.servico'),
        ),
    ]
