# Generated by Django 5.2.1 on 2025-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da Fatura'),
        ),
    ]
