# Generated by Django 5.2.1 on 2025-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_alter_fatura_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Atual'),
        ),
    ]
