# Generated by Django 5.2.1 on 2025-07-01 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.fatura')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretaria.servico')),
            ],
            options={
                'unique_together': {('fatura', 'servico')},
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='itens',
            field=models.ManyToManyField(through='secretaria.FaturaServico', to='secretaria.servico'),
        ),
    ]
