# Generated by Django 5.2.1 on 2025-07-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0011_matricula_curso_turma_curso'),
        ('secretaria', '0005_faturaservico_fatura_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso')),
            ],
            options={
                'verbose_name': 'Pré‑Matrícula',
                'verbose_name_plural': 'Pré‑Matrículas',
                'ordering': ['-data_solic'],
            },
        ),
    ]
