# Generated by Django 5.2.1 on 2025-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_prematricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('SUSPENSO', 'Suspenso'), ('TRANCADO', 'Trancado'), ('FORMADO', 'Formado'), ('TRANSFERIDO', 'Transferido'), ('DESISTENTE', 'Desistente')], default='ATIVO', max_length=12, verbose_name='Status'),
        ),
    ]
