# Generated by Django 5.2.1 on 2025-07-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_alter_aluno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturaservico',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário'),
        ),
    ]
