# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: 2025, 2025-2026 ou 2025.1', max_length=20, unique=True)),
                ('data_inicio', models.DateField(help_text='Data de início do ano letivo')),
                ('data_fim', models.DateField(help_text='Data de término do ano letivo')),
                ('ativo', models.BooleanField(default=False, help_text='Marcar apenas um ano como ativo')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('TRANSFERIDO', 'TRANSFERIDO'), ('DESLIGADO', 'DESLIGADO')], default='ATIVO', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N1')),
                ('nota2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N2')),
                ('nota3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N3')),
                ('media_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Parcial')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Final')),
                ('situacao', models.CharField(blank=True, choices=[('APROVADO', 'APROVADO'), ('REPROVADO', 'REPROVADO')], max_length=10, verbose_name='Situação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='PreRematricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
            ],
            options={
                'verbose_name': 'Pré‑Rematrícula',
                'verbose_name_plural': 'Pré‑Rematrículas',
                'ordering': ['-data_solic'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Turma')),
                ('nivel', models.CharField(choices=[('10º Ano', '10º Ano'), ('11º Ano', '11º Ano'), ('12º Ano', '12º Ano'), ('13º Ano', '13º Ano')], max_length=20, verbose_name='Ano/Nível')),
                ('turno', models.CharField(choices=[('MANHÃ', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('professor_responsavel', models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_responsavel', models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Turma-Disciplina',
                'verbose_name_plural': 'Turmas-Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')], verbose_name='Trimestre')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='pedagogico/boletins/', verbose_name='Arquivo Boletim (PDF)')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletins_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Boletim',
                'verbose_name_plural': 'Boletins',
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedagogico.anoletivo')),
            ],
            options={
                'verbose_name': 'Evento no Calendário',
                'verbose_name_plural': 'Calendário de Eventos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas/ano)')),
                ('professor_responsavel', models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
                'unique_together': {('nome',)},
            },
        ),
    ]
