# Generated by Django 5.2.1 on 2025-05-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Turma')),
                ('nivel', models.CharField(choices=[('10º Ano', '10º Ano'), ('11º Ano', '11º Ano'), ('12º Ano', '12º Ano'), ('13º Ano', '13º Ano')], max_length=20, verbose_name='Ano/Nível')),
                ('turno', models.CharField(choices=[('MANHÃ', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('professor_responsavel', models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas/ano)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
                'unique_together': {('nome',)},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N1')),
                ('nota2', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N2')),
                ('nota3', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='N3')),
                ('media_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Parcial')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Final')),
                ('situacao', models.CharField(blank=True, choices=[('APROVADO', 'APROVADO'), ('REPROVADO', 'REPROVADO')], max_length=10, verbose_name='Situação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedagogico.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('aluno', 'turma', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(verbose_name='Data de Matrícula')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('TRANSFERIDO', 'TRANSFERIDO'), ('DESLIGADO', 'DESLIGADO')], default='ATIVO', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='secretaria.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')], verbose_name='Trimestre')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='pedagogico/boletins/', verbose_name='Arquivo Boletim (PDF)')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletins_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'Boletim',
                'verbose_name_plural': 'Boletins',
                'unique_together': {('turma', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_turmas', to='pedagogico.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplinas', to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'Turma-Disciplina',
                'verbose_name_plural': 'Turmas-Disciplinas',
                'unique_together': {('turma', 'disciplina')},
            },
        ),
    ]
