# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedagogico', '0001_initial'),
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='secretaria.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='pedagogico.anoletivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='secretaria.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='pedagogico.anoletivo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedagogico.disciplina'),
        ),
        migrations.AddField(
            model_name='prerematricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno'),
        ),
        migrations.AddField(
            model_name='prerematricula',
            name='ano_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pedagogico.anoletivo'),
        ),
        migrations.AddField(
            model_name='prerematricula',
            name='curso_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='pedagogico.anoletivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
        ),
        migrations.AddField(
            model_name='prerematricula',
            name='turma_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rematriculas_origem', to='pedagogico.turma'),
        ),
        migrations.AddField(
            model_name='nota',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='pedagogico.turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='pedagogico.turma'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='pedagogico.turma'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='turma_disciplinas', to='pedagogico.anoletivo'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_turmas', to='pedagogico.disciplina'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turma_disciplinas', to='pedagogico.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='calendario',
            unique_together={('ano_letivo', 'data', 'titulo')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'turma', 'disciplina')},
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'ano_letivo'), name='unique_matricula_aluno_ano'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
        migrations.AlterUniqueTogether(
            name='boletim',
            unique_together={('turma', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='turmadisciplina',
            unique_together={('turma', 'disciplina')},
        ),
    ]
