# Generated by Django 5.2.1 on 2025-06-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: 2025, 2025-2026 ou 2025.1', max_length=20, unique=True)),
                ('data_inicio', models.DateField(help_text='Data de início do ano letivo')),
                ('data_fim', models.DateField(help_text='Data de término do ano letivo')),
                ('ativo', models.BooleanField(default=False, help_text='Marcar apenas um ano como ativo')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pedagogico.anoletivo')),
            ],
            options={
                'verbose_name': 'Evento no Calendário',
                'verbose_name_plural': 'Calendário de Eventos',
                'ordering': ['data'],
                'unique_together': {('ano_letivo', 'data', 'titulo')},
            },
        ),
    ]
