# Generated by Django 5.2.1 on 2025-06-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0002_anoletivo_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='ano_letivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.anoletivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='ano_letivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.anoletivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.anoletivo'),
            preserve_default=False,
        ),
    ]
