# Generated by Django 5.2.1 on 2025-06-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0003_matricula_ano_letivo_nota_ano_letivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                to='pedagogico.AnoLetivo',
                default=1,      # atribui valor 1 a todas as Turmas existentes
            ),
            preserve_default=False,
        ),
    ]
