# Generated by Django 5.2.1 on 2025-06-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0004_alter_turma_ano_letivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='pedagogico.anoletivo'),
        ),
    ]
