# Generated by Django 5.2.1 on 2025-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0005_alter_turma_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='professor_responsavel',
            field=models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável'),
        ),
    ]
