# Generated by Django 5.2.1 on 2025-06-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0006_disciplina_professor_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='pedagogico.anoletivo'),
            preserve_default=False,
        ),
    ]
