# Generated by Django 5.2.1 on 2025-06-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0007_alter_turma_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmadisciplina',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='turma_disciplinas', to='pedagogico.anoletivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='professor_responsavel',
            field=models.CharField(blank=True, help_text='Nome ou FK para Colaborador (futuro)', max_length=150, verbose_name='Professor Responsável'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='pedagogico.anoletivo'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='ano_letivo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='pedagogico.anoletivo'),
        ),
    ]
