# Generated by Django 5.2.1 on 2025-06-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0008_turmadisciplina_ano_letivo_and_more'),
        ('secretaria', '0003_alter_fatura_valor_atual'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'ano_letivo'), name='unique_matricula_aluno_ano'),
        ),
    ]
