# Generated by Django 5.2.1 on 2025-07-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0010_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
            preserve_default=False,
        ),
    ]
