# Generated by Django 5.2.1 on 2025-07-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0011_matricula_curso_turma_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso'),
        ),
    ]
