# Generated by Django 5.2.1 on 2025-07-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0013_alter_matricula_curso'),
        ('secretaria', '0006_prematricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRematricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solic', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno')),
                ('ano_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pedagogico.anoletivo')),
                ('curso_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.curso')),
                ('turma_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rematriculas_origem', to='pedagogico.turma')),
            ],
            options={
                'verbose_name': 'Pré‑Rematrícula',
                'verbose_name_plural': 'Pré‑Rematrículas',
                'ordering': ['-data_solic'],
            },
        ),
    ]
