# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=200, verbose_name='Nome do Arquivo')),
                ('status', models.CharField(choices=[('SUCESSO', 'SUCESSO'), ('FALHA', 'FALHA')], max_length=10, verbose_name='Status')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes (stdout/stderr)')),
                ('executado_por', models.CharField(max_length=50, verbose_name='Executado por')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Logs de Backup',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlite3', 'SQLite')], max_length=15, verbose_name='Engine do Banco')),
                ('db_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('db_user', models.CharField(blank=True, max_length=50, verbose_name='Usuário do Banco')),
                ('db_password', models.CharField(blank=True, max_length=100, verbose_name='Senha do Banco')),
                ('db_host', models.CharField(default='localhost', max_length=100, verbose_name='Host')),
                ('db_port', models.PositiveIntegerField(default=5432, verbose_name='Porta')),
                ('backup_local_path', models.CharField(max_length=250, verbose_name='Diretório de Backup')),
                ('backup_filename_pattern', models.CharField(default='backup_%Y%m%d_%H%M%S.sql', help_text="Padrão para o nome do arquivo de backup. Use strftime para datas. Exemplo: 'backup_%%Y%%m%%d_%%H%%M%%S.sql'", max_length=100, verbose_name='Padrão do Nome do Backup')),
                ('smtp_host', models.CharField(blank=True, max_length=100, verbose_name='SMTP Host')),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='SMTP Port')),
                ('smtp_user', models.CharField(blank=True, max_length=100, verbose_name='SMTP Usuário')),
                ('smtp_password', models.CharField(blank=True, max_length=100, verbose_name='SMTP Senha')),
                ('whatsapp_api_url', models.CharField(blank=True, max_length=200, verbose_name='WhatsApp API URL')),
                ('whatsapp_api_token', models.CharField(blank=True, max_length=200, verbose_name='WhatsApp API Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração Inicial',
                'verbose_name_plural': 'Configurações Iniciais',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='Anonymous', max_length=150, verbose_name='Usuário')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('mensagem_erro', models.TextField(verbose_name='Mensagem de Erro')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('data_ocorrencia', models.DateTimeField(auto_now_add=True, verbose_name='Data de Ocorrência')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_id', models.IntegerField(blank=True, null=True, verbose_name='Fatura ID')),
                ('destinatario', models.CharField(max_length=150, verbose_name='Destinatário')),
                ('meio', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=10, verbose_name='Meio')),
                ('status_envio', models.CharField(choices=[('SUCESSO', 'SUCESSO'), ('FALHA', 'FALHA')], max_length=15, verbose_name='Status')),
                ('mensagem', models.TextField(verbose_name='Mensagem Enviada')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes (resposta API)')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
