# Generated by Django 5.2.1 on 2025-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinicial',
            name='backup_filename_pattern',
            field=models.CharField(default='backup_%Y%m%d_%H%M%S.sql', help_text="Padrão para o nome do arquivo de backup. Use strftime para datas. Exemplo: 'backup_%%Y%%m%%d_%%H%%M%%S.sql'", max_length=100, verbose_name='Padrão do Nome do Backup'),
        ),
    ]
