# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.anoletivo'),
        ),
    ]
