# Generated by Django 5.2.1 on 2025-06-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoinicial_backup_filename_pattern'),
        ('pedagogico', '0009_matricula_unique_matricula_aluno_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.anoletivo')),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
