# Generated by Django 5.2.1 on 2025-09-07 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BemPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('MOVEIS', 'Móveis'), ('EQUIPAMENTOS', 'Equipamentos'), ('VEICULOS', 'Veículos'), ('IMÓVEIS', 'Imóveis'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Aquisição')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('vida_util_anos', models.PositiveIntegerField(verbose_name='Vida Útil (anos)')),
                ('localizacao', models.CharField(blank=True, max_length=150, verbose_name='Localização')),
                ('depreciacao_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Depreciação Acumulada')),
                ('valor_contabil_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Contábil Líquido')),
                ('arquivo_documento', models.FileField(blank=True, null=True, upload_to='administrativo/patrimonio/', verbose_name='Arquivo Nota Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Bem de Patrimônio',
                'verbose_name_plural': 'Bens de Patrimônio',
                'ordering': ['-data_aquisicao'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=50, unique=True, verbose_name='Documento (BI)')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(choices=[('RH', 'Recursos Humanos'), ('TESOURARIA', 'Tesouraria'), ('PATRIMONIO', 'Patrimônio'), ('CONTABILIDADE', 'Contabilidade'), ('SUBDIRECAO PEDAGOGICA', 'Subdireção Pedagógica'), ('SUBDIRECAO ADMINISTRATIVA', 'Subdireção Administrativa'), ('DIRCAO GERAL', 'Direção Geral'), ('OUTRO', 'Outro')], max_length=32, verbose_name='Departamento')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salário Base')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10, verbose_name='Tipo')),
                ('posicao', models.CharField(choices=[('DEBITO', 'Débito (+)'), ('CREDITO', 'Crédito (+)')], max_length=10, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_credito', to='administrativo.contacontabil', verbose_name='Conta Crédito')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_debito', to='administrativo.contacontabil', verbose_name='Conta Débito')),
                ('lancado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_contabeis', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Formato deve ser YYYY-MM (ex: 2025-04)', regex='^\\d{4}-\\d{2}$')])),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Extras')),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descontos')),
                ('bonificacoes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonificações')),
                ('salario_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário Bruto')),
                ('inss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='INSS')),
                ('irt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='IRT')),
                ('salario_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salário Líquido')),
                ('arquivo_holerite', models.FileField(blank=True, null=True, upload_to='administrativo/holerites/', verbose_name='Holerite (PDF)')),
                ('data_processamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Processamento')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarios', to='administrativo.colaborador')),
                ('processado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarios_processados', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'verbose_name': 'Salário',
                'verbose_name_plural': 'Salários',
                'unique_together': {('colaborador', 'mes_referencia')},
            },
        ),
    ]
