# Generated by Django 5.2.1 on 2025-06-01 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='data_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salario',
            name='mes_referencia',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Formato deve ser YYYY-MM (ex: 2025-04)', regex='^\\d{4}-\\d{2}$')]),
        ),
    ]
