# Generated by Django 5.2.1 on 2025-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_salario_data_referencia_alter_salario_mes_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='departamento',
            field=models.CharField(choices=[('RH', 'Recursos Humanos'), ('TESOURARIA', 'Tesouraria'), ('PATRIMONIO', 'Patrimônio'), ('CONTABILIDADE', 'Contabilidade'), ('SUBDIRECAO PEDAGOGICA', 'Subdireção Pedagógica'), ('SUBDIRECAO ADMINISTRATIVA', 'Subdireção Administrativa'), ('DIRCAO GERAL', 'Direção Geral'), ('OUTRO', 'Outro')], max_length=32, verbose_name='Departamento'),
        ),
    ]
