# Generated by Django 5.2.1 on 2025-07-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_colaborador_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='conta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_credito', to='administrativo.contacontabil', verbose_name='Conta Crédito'),
        ),
        migrations.AlterField(
            model_name='lancamentocontabil',
            name='conta_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_debito', to='administrativo.contacontabil', verbose_name='Conta Débito'),
        ),
    ]
