# Generated by Django 5.2.1 on 2025-07-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_contacontabil_alter_lancamentocontabil_conta_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacontabil',
            name='posicao',
            field=models.CharField(choices=[('DEBITO', 'Débito (+)'), ('CREDITO', 'Crédito (+)')], default=1, max_length=10, verbose_name='Posição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacontabil',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], default=1, max_length=10, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
